#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
# ISMS Builder – Let's Encrypt Zertifikat einrichten / erneuern
#
# Unterstützte Modi:
#   standalone  – certbot öffnet eigenen HTTP-Server (Port 80 muss frei sein)
#   webroot     – certbot legt Challenge-Datei in einen Web-Root
#   dns         – DNS-TXT-Record manuell setzen (kein offener Port nötig)
#
# Verwendung:
#   bash scripts/letsencrypt.sh            # interaktiv
#   bash scripts/letsencrypt.sh renew      # Zertifikat erneuern
#   bash scripts/letsencrypt.sh status     # Zertifikat-Status anzeigen
# ─────────────────────────────────────────────────────────────────
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_DIR/.env"
SSL_DIR="$PROJECT_DIR/ssl"

# ── Farben ────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()    { echo -e "${CYAN}▶ $*${NC}"; }
ok()      { echo -e "${GREEN}✓ $*${NC}"; }
warn()    { echo -e "${YELLOW}⚠ $*${NC}"; }
err()     { echo -e "${RED}✗ Fehler: $*${NC}"; exit 1; }
step()    { echo -e "\n${BOLD}── $* ──────────────────────────────────${NC}"; }

# ── Hilfsfunktionen .env ─────────────────────────────────────────
env_set() {
  local key="$1" val="$2"
  if grep -qE "^#?${key}=" "$ENV_FILE" 2>/dev/null; then
    sed -i "s|^#\?${key}=.*|${key}=${val}|" "$ENV_FILE"
  else
    echo "${key}=${val}" >> "$ENV_FILE"
  fi
}

env_get() {
  grep -E "^${1}=" "$ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '"'
}

# ── certbot prüfen / installieren ────────────────────────────────
check_certbot() {
  if ! command -v certbot &>/dev/null; then
    warn "certbot ist nicht installiert."
    echo ""
    echo " Installation:"
    echo "   Ubuntu/Debian : sudo apt install certbot"
    echo "   Arch Linux    : sudo pacman -S certbot"
    echo "   Fedora/RHEL   : sudo dnf install certbot"
    echo "   Snap          : sudo snap install --classic certbot"
    echo "   pip           : pip install certbot"
    echo ""
    err "Bitte certbot installieren und das Script erneut ausführen."
  fi
  ok "certbot gefunden: $(certbot --version 2>&1 | head -1)"
}

# ── Symlinks ins ssl/ Verzeichnis ────────────────────────────────
link_certs() {
  local domain="$1"
  local le_dir="/etc/letsencrypt/live/${domain}"

  [ -d "$le_dir" ] || err "Let's Encrypt Verzeichnis nicht gefunden: $le_dir"

  mkdir -p "$SSL_DIR"
  ln -sf "${le_dir}/fullchain.pem" "$SSL_DIR/cert.pem"
  ln -sf "${le_dir}/privkey.pem"   "$SSL_DIR/key.pem"

  env_set SSL_CERT_FILE "ssl/cert.pem"
  env_set SSL_KEY_FILE  "ssl/key.pem"

  ok "Symlinks erstellt: ssl/cert.pem → ${le_dir}/fullchain.pem"
  ok "Symlinks erstellt: ssl/key.pem  → ${le_dir}/privkey.pem"
  ok ".env aktualisiert"
}

# ── Zertifikat-Info anzeigen ─────────────────────────────────────
show_cert_info() {
  local cert="$1"
  [ -f "$cert" ] || { warn "Zertifikat nicht gefunden: $cert"; return; }
  echo ""
  info "Zertifikat-Details:"
  openssl x509 -in "$cert" -noout \
    -subject -issuer -dates -fingerprint 2>/dev/null | sed 's/^/   /'

  # Ablauf-Warnung
  local expiry_epoch
  expiry_epoch=$(openssl x509 -in "$cert" -noout -enddate 2>/dev/null \
    | cut -d= -f2 | xargs -I{} date -d {} +%s 2>/dev/null || echo 0)
  local now_epoch
  now_epoch=$(date +%s)
  local days_left=$(( (expiry_epoch - now_epoch) / 86400 ))

  if [ "$days_left" -lt 0 ]; then
    echo -e "   ${RED}✗ ABGELAUFEN${NC}"
  elif [ "$days_left" -lt 14 ]; then
    echo -e "   ${RED}⚠ Läuft in ${days_left} Tagen ab – DRINGEND ERNEUERN!${NC}"
  elif [ "$days_left" -lt 30 ]; then
    echo -e "   ${YELLOW}⚠ Läuft in ${days_left} Tagen ab${NC}"
  else
    echo -e "   ${GREEN}✓ Gültig noch ${days_left} Tage${NC}"
  fi
}

# ── Auto-Renewal cron einrichten ─────────────────────────────────
setup_renewal_cron() {
  local domain="$1"
  local le_dir="/etc/letsencrypt/live/${domain}"

  # Hook-Script das nach Renewal Symlinks aktualisiert + Server neustartet
  local hook_dir="/etc/letsencrypt/renewal-hooks/deploy"
  local hook_file="${hook_dir}/isms-restart.sh"

  if [ -d "$hook_dir" ] && [ "$(id -u)" = "0" ]; then
    cat > "$hook_file" << HOOK
#!/bin/bash
# Auto-generated by ISMS Builder letsencrypt.sh
ln -sf ${le_dir}/fullchain.pem ${SSL_DIR}/cert.pem
ln -sf ${le_dir}/privkey.pem   ${SSL_DIR}/key.pem
bash ${PROJECT_DIR}/stop.sh 2>/dev/null || true
sleep 1
bash ${PROJECT_DIR}/start.sh
HOOK
    chmod +x "$hook_file"
    ok "Deploy-Hook eingerichtet: $hook_file"
  fi

  # Systemd-Timer hat Vorrang vor cron wenn vorhanden
  if systemctl list-timers 2>/dev/null | grep -q certbot; then
    ok "Systemd certbot.timer ist aktiv – Auto-Renewal bereits eingerichtet"
    return
  fi

  # Cron-Fallback
  local renew_cmd="certbot renew --quiet"
  local cron_line="0 3 * * * $renew_cmd"
  ( crontab -l 2>/dev/null | grep -v "certbot renew"; echo "$cron_line" ) | crontab -
  ok "Cron-Job eingerichtet: täglich 03:00 Uhr → certbot renew"
}

# ═════════════════════════════════════════════════════════════════
# HAUPTPROGRAMM
# ═════════════════════════════════════════════════════════════════

ACTION="${1:-}"

echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD} ISMS Builder – Let's Encrypt Zertifikat${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

# ── Status anzeigen ──────────────────────────────────────────────
if [ "$ACTION" = "status" ]; then
  CERT_FILE=$(env_get SSL_CERT_FILE)
  if [ -z "$CERT_FILE" ]; then
    warn "Kein SSL-Zertifikat in .env konfiguriert."
  else
    [ "${CERT_FILE:0:1}" != "/" ] && CERT_FILE="$PROJECT_DIR/$CERT_FILE"
    show_cert_info "$CERT_FILE"
  fi
  echo ""
  info "Alle Let's Encrypt Zertifikate auf diesem System:"
  sudo certbot certificates 2>/dev/null || certbot certificates 2>/dev/null || warn "certbot nicht installiert"
  exit 0
fi

# ── Erneuern ─────────────────────────────────────────────────────
if [ "$ACTION" = "renew" ]; then
  check_certbot
  step "Zertifikat erneuern"
  sudo certbot renew 2>/dev/null || certbot renew
  CERT_FILE=$(env_get SSL_CERT_FILE)
  [ "${CERT_FILE:0:1}" != "/" ] && CERT_FILE="$PROJECT_DIR/$CERT_FILE"
  show_cert_info "$CERT_FILE"
  warn "Starte den ISMS-Server neu damit das neue Zertifikat geladen wird."
  exit 0
fi

# ── Neu einrichten ────────────────────────────────────────────────
check_certbot

echo ""
echo " Gib deine Domain und E-Mail an:"
echo ""
read -rp " Domain (z.B. isms.meinefirma.de): " DOMAIN
[ -z "$DOMAIN" ] && err "Keine Domain eingegeben."

read -rp " Weitere Domains/Subdomains? (leer lassen falls nein): " EXTRA_DOMAINS

read -rp " E-Mail für Ablauf-Benachrichtigungen: " LE_EMAIL
[ -z "$LE_EMAIL" ] && err "Keine E-Mail eingegeben."

echo ""
echo " Validierungsmethode:"
echo "   1) Standalone  – certbot startet eigenen HTTP-Server (Port 80 muss frei sein)"
echo "   2) Webroot     – certbot legt Datei in bestehenden Web-Root (Nginx/Apache)"
echo "   3) DNS-01      – DNS-TXT-Record manuell setzen (kein Port nötig, auch für Wildcard)"
echo ""
read -rp " Methode [1-3]: " METHOD

# Domain-Parameter aufbauen
DOMAIN_ARGS="-d $DOMAIN"
if [ -n "$EXTRA_DOMAINS" ]; then
  for d in $EXTRA_DOMAINS; do
    DOMAIN_ARGS="$DOMAIN_ARGS -d $d"
  done
fi

# Staging-Modus (vermeidet Rate-Limits beim Testen)
echo ""
read -rp " Staging-Modus aktivieren? (empfohlen zum Testen) [j/N]: " STAGING
STAGING_FLAG=""
[ "${STAGING,,}" = "j" ] && STAGING_FLAG="--staging" && warn "Staging-Modus aktiv – kein vertrauenswürdiges Zertifikat!"

case "$METHOD" in

# ── Standalone ────────────────────────────────────────────────────
1)
  step "Standalone-Validierung"
  info "Stoppe ISMS-Server kurz (Port 80 wird benötigt)…"
  bash "$PROJECT_DIR/stop.sh" 2>/dev/null || true

  # Temporär Port 80 freimachen falls nötig
  PORT80_PID=$(ss -tlnp | grep ':80 ' | grep -oP 'pid=\K[0-9]+' | head -1 || true)
  if [ -n "$PORT80_PID" ]; then
    warn "Port 80 belegt von PID $PORT80_PID – versuche zu beenden…"
    sudo kill "$PORT80_PID" 2>/dev/null || kill "$PORT80_PID" 2>/dev/null || true
    sleep 1
  fi

  info "Starte certbot standalone…"
  sudo certbot certonly \
    --standalone \
    --non-interactive \
    --agree-tos \
    --email "$LE_EMAIL" \
    $DOMAIN_ARGS \
    $STAGING_FLAG

  link_certs "$DOMAIN"
  setup_renewal_cron "$DOMAIN"

  info "Starte ISMS-Server wieder…"
  bash "$PROJECT_DIR/start.sh"
  ;;

# ── Webroot ───────────────────────────────────────────────────────
2)
  step "Webroot-Validierung"
  echo ""
  read -rp " Pfad zum Web-Root (z.B. /var/www/html): " WEBROOT
  [ -z "$WEBROOT" ] && err "Kein Webroot angegeben."
  [ -d "$WEBROOT" ] || err "Verzeichnis nicht gefunden: $WEBROOT"

  info "Starte certbot webroot…"
  sudo certbot certonly \
    --webroot \
    --webroot-path "$WEBROOT" \
    --non-interactive \
    --agree-tos \
    --email "$LE_EMAIL" \
    $DOMAIN_ARGS \
    $STAGING_FLAG

  link_certs "$DOMAIN"
  setup_renewal_cron "$DOMAIN"
  ;;

# ── DNS-01 ────────────────────────────────────────────────────────
3)
  step "DNS-01 Validierung (manuell)"
  echo ""
  warn "Diese Methode erfordert manuelle DNS-Einträge."
  echo ""
  echo " Ablauf:"
  echo "  1. certbot zeigt dir einen TXT-Eintrag für _acme-challenge.${DOMAIN}"
  echo "  2. Du trägst diesen Eintrag bei deinem DNS-Anbieter ein"
  echo "  3. Warte bis der Eintrag propagiert ist (60–300 Sek.)"
  echo "  4. Drücke Enter in certbot um fortzufahren"
  echo ""
  read -rp " Weiter? [Enter]" _

  sudo certbot certonly \
    --manual \
    --preferred-challenges dns \
    --agree-tos \
    --email "$LE_EMAIL" \
    $DOMAIN_ARGS \
    $STAGING_FLAG

  link_certs "$DOMAIN"
  setup_renewal_cron "$DOMAIN"
  ;;

*)
  err "Ungültige Auswahl."
  ;;
esac

# ── Abschluss ─────────────────────────────────────────────────────
CERT_PATH="$PROJECT_DIR/ssl/cert.pem"
[ -L "$CERT_PATH" ] && CERT_PATH=$(readlink -f "$CERT_PATH")
show_cert_info "$CERT_PATH"

echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD} Fertig!${NC}"
echo ""
echo " Aktuelle SSL-Konfiguration:"
grep -E "^SSL_" "$ENV_FILE" | sed 's/^/   /' || echo "   (keine)"
echo ""
echo " Nützliche Befehle:"
echo "   Status prüfen  : bash scripts/letsencrypt.sh status"
echo "   Erneuern       : bash scripts/letsencrypt.sh renew"
echo "   Alle Zertifikate: sudo certbot certificates"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
